### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by JerickoDG** [sovit-123/fasterrcnn-pytorch-training-pipeline#107]
Hi, may I ask if you know how I can fix this error I encountered? It appeared after showing the details/specs of the model. 

**NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].**

I hope for your response. Thank you.

**Comment by JerickoDG** [comment]
- I am using **Python 3.9.18** from Anaconda Environments
- CUDA 11.8 and installed Pytorch CUDA-enabled using this command from the website: **pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118**

**Comment by JerickoDG** [comment]
I solved it. I just downgraded my Python 3.11.x to 3.9.18.

By the way, may I ask what is the model, "fasterrcnn_mobilenetv3_large_320_fpn"? Is it different from Faster RCNN or is it MobileNetV3 model?

**Comment by sovit-123** [comment]
So, the above model has a Faster RCNN head with MobileNetV3 Large backbone.

**Comment by JerickoDG** [comment]
Okay, got it. By any chance, do you also have training pipeline for Single Shot Detector or SSD (preferably with MobileNetV2 as the backbone) using a custom dataset? Thank you again.

**Comment by sovit-123** [comment]
I don't have yet. However, I am planning to create an all-in-one detection repository that will have all types of detection models including these Faster RCNN ones. I want a library and the training pipeline to be as easy as in this library.

**Comment by JerickoDG** [comment]
Okay. Looking forward to it. Thank you very much, sovit-123.
