### ISSUE TITLE
self.eval_imgs[iou_type] = np.concatenate(self.eval_imgs[iou_type], 2)   File "<__array_function__ internals>", line 200, in concatenate

### ISSUE THREAD

**Issue by HassanBinHaroon** [sovit-123/fasterrcnn-pytorch-training-pipeline#111]
self.eval_imgs[iou_type] = np.concatenate(self.eval_imgs[iou_type], 2)
  File "<__array_function__ internals>", line 200, in concatenate

Error in coco_eval.py

**Comment by sovit-123** [comment]
Hello @HassanBinHaroon 
Can you please provide some more details?
What OS are you using? In general, it is highly recommended to use Linux based OS or WSL with Windows.
If every requirement is installed correctly, especially pycocotools?
Also, please provide the entire error trace.

**Comment by HassanBinHaroon** [comment]
Hi There @sovit-123,

 Sure, Following are the details:
 
 OS Name: Ubuntu 20.04
About Requirements: Everything is installed correctly. There wasn't any error. It was really smooth when I installed Python 3.8. The screenshot is attached of pycocotools installation. 
![pycocotools_installed](https://github.com/sovit-123/fasterrcnn-pytorch-training-pipeline/assets/104098902/aaa887bc-c566-4c6b-8846-6596fb4da2de)

First Error:
Initially I encountered the "ZeroDivisionError:" at the following line. **_iterable_** variable showed value equal to zero (I've mentioned that in the image). Then I added epsilon so time being for this error resolution.

Second Error (Complete Trace):    
![error2](https://github.com/sovit-123/fasterrcnn-pytorch-training-pipeline/assets/104098902/7233a4a6-293b-4a7e-a6b1-6b4ef87bf802)

**Comment by sovit-123** [comment]
Thanks for the additional information. I may need to reproduce the error to know exactly what's going on. Do you think you can somehow share a few samples from your dataset, your dataset YAML file, and the command that you are using?

**Comment by HassanBinHaroon** [comment]
Sure, I am going to share it. That's really appreciated because using some samples from my dataset would reveal the actual cause.

**Comment by sovit-123** [comment]
Hello. It is a simple error in your YAML file. The validation dataset folder name should be `val` but you have named it `valid`. That's why there is not data sample and producing an iterable error.

**Comment by HassanBinHaroon** [comment]
Thank You SO much!

Code is being executed.
