### ISSUE TITLE
about VOC2007 dataset training

### ISSUE THREAD

**Issue by CharisWg** [sovit-123/fasterrcnn-pytorch-training-pipeline#120]
I do not understand what you mean TRAIN_DIR_IMAGES: '../input/voc_07_12/voc_xml_dataset/train/images'
Are the XMLs in the Annotation files? or the text in the
./fasterrcnn-pytorch-training-pipeline-main/data/VOC2007/ImageSets/Segmentation/train.txt ???

**Comment by sovit-123** [comment]
The code does not use text files to map the annotations for Pascal VOC or any other dataset. It uses XML annotation format for training. I think the [training on custom dataset section](https://github.com/sovit-123/fasterrcnn-pytorch-training-pipeline?tab=readme-ov-file#train-on-custom-dataset) will clarify your doubt.

**Comment by CharisWg** [comment]
I solved this, thank you so much for replying quickly.

**Comment by sovit-123** [comment]
Welcome. Closing the issue for now.
