### ISSUE TITLE
file names not logged when using option --log-json

### ISSUE THREAD

**Issue by jgmv** [sovit-123/fasterrcnn-pytorch-training-pipeline#133]
Hello,
In the  'log.json' file generated when using option '--log-json', all images have the same 'file_name': "frame1.jpg". Can this be set to write the original file name (e.g. l.293 in 'logging.py')?
Thanks!

**Comment by sovit-123** [comment]
Hello @jgmv 
I will check that.

**Comment by jgmv** [comment]
Thanks for accepting the changes!
