### ISSUE TITLE
'log.json' file contains incorrect bounding boxes

### ISSUE THREAD

**Issue by jgmv** [sovit-123/fasterrcnn-pytorch-training-pipeline#135]
The 'log.json' file generated when using the option 'inference.py --log-json' contains more bounding boxes than those detected in the images. This often includes objects from classes not displayed in the images.

**Comment by sovit-123** [comment]
Will take a look into it ASAP. Need to check the code. Maybe a threshold issue.

**Comment by jgmv** [comment]
Yes, I think the problem is that the boxes are saved before the threshold is applied

**Comment by joshua-atolagbe** [comment]
@sovit-123 Is this solved?

**Comment by sovit-123** [comment]
@joshua-atolagbe @jgmv I just pushed an update. It's corrected now. Please pull.
