### ISSUE TITLE
Transfer Learning or Finetune method

### ISSUE THREAD

**Issue by Subhankhan41** [sovit-123/fasterrcnn-pytorch-training-pipeline#151]
Hi Sovit,

Thanks again for producing great tutorials for us to learn deep learning. I tried the Faster RCNN with my custom dataset and it works fine. Now, after completing the training, I want to finetune my model and instead of starting from scratch I want to start the new training from the best_model.pth. Could you please let me know how can I perform transfer learning or finetuning?

Thanks

**Comment by sovit-123** [comment]
Sure. If you want to use previously trained weights, you can use the same training command with some additional changes to the command line arguments.

`python train.py --weights <path to the weights.pth file> --epochs <num epochs> --resume-training`

* `--weights`: This is the path to the weights file that you trained earlier.
* `--epochs`: This should be higher than the previous training. For example, if previous training was 10 epochs, and you want to train for 10 more epochs, then it should be 20.
* `--resume-training`: This is a boolean argument which let's the script know that it has to pick up all the graphs and plots from where they were left off and resume the plotting.

With the above command, provide the rest of the command line arguments like dataset YAML path and others.

I hope this helps.

**Comment by Subhankhan41** [comment]
Great. Thanks a lot Sovit, you're a legend!

**Comment by Subhankhan41** [comment]
Great. Thanks a lot Sovit, you're a legend!
