### ISSUE TITLE
Faster RCNN MobileNetV3 Onnx conversion issue

### ISSUE THREAD

**Issue by Subhankhan41** [sovit-123/fasterrcnn-pytorch-training-pipeline#154]
Hi @sovit-123 

I tried to convert the onnx model of the Faster RCNN MobileNetV3 but having the following errors:
Input shape: torch.Size([1, 3, 960, 960])
2024-09-10 09:34:40.9769638 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'Reshape_1486' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:36 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{15,7}, requested shape:{-1,4}

Traceback (most recent call last):
  File "C:\Users\Subhan.Khan\Python_Code\Test_SSD\FasterRCNN\Faster_RCNN\onnx_inference_video.py", line 133, in <module>
    main(args)
  File "C:\Users\Subhan.Khan\Python_Code\Test_SSD\FasterRCNN\Faster_RCNN\onnx_inference_video.py", line 91, in main
    preds = ort_session.run(None, {ort_session.get_inputs()[0].name: to_numpy(image)})
  File "C:\Users\Subhan.Khan\AppData\Local\anaconda3\envs\FRCNN\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1486' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:36 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{15,7}, requested shape:{-1,4}

I tried other models and they are working. Any idea what's wrong with the MobileNet version?

**Comment by sovit-123** [comment]
Hi @Subhankhan41 
Can you please let me know the command that you used to execute it? Also, if you can give more information about the PyTorch, ONNX, versions, I maybe able to debug it.
However, usually, MobileNet versions of Faster RCNN face issues sometimes. This is because of some internal reshape layer is not handled by ONNX.

**Comment by Subhankhan41** [comment]
Hi @sovit-123 thanks for the response, I have fixed the issue. I customized my conversion code to be dynamic as follows:

import io
import torch
import torch.onnx
from models.create_fasterrcnn_model import create_model
NUM_CLASSES = 10
DEVICE = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

checkpoint = torch.load('outputs/best_model.pth', map_location=DEVICE)
print(create_model)
build_model = create_model[checkpoint['model_name']]
model = build_model(num_classes=NUM_CLASSES, coco_model=False)
model.load_state_dict(checkpoint['model_state_dict'])
model.to(DEVICE).eval()

# Define the input tensor with 3 channels for the Faster R-CNN model
batch_size = 32 #Example
x = torch.randn(1, 3, 320, 320, requires_grad=True).to(DEVICE) #Here we can change it to 640 640 as well

# Run the model once to check output structure
with torch.no_grad():
    output = model(x)  # Faster R-CNN output is typically a dict

# Example: Extract the tensor output from the dictionary
# Assuming we're only interested in the predicted bounding boxes
output_tensor = output[0]['boxes']  # Adjust according to your model's output

# Export the model to ONNX
torch.onnx.export(
    model, 
    x,  # Your input tensor (e.g., torch.randn(1, 3, 320, 320))
    "model_dynamic.onnx",  # Name of the ONNX model to save
    export_params=True,
    opset_version=11,  # You can adjust the opset version if needed
    do_constant_folding=True,
    input_names=['input'],
    output_names=['boxes', 'labels', 'scores'],
    dynamic_axes={'input': {0: 'batch_size', 2: 'height', 3: 'width'},  # Allow dynamic height and width
                  'boxes': {0: 'batch_size'},
                  'labels': {0: 'batch_size'},
                  'scores': {0: 'batch_size'}}
)

**Comment by sovit-123** [comment]
Glad to know that. Thanks for the update.
