### ISSUE TITLE
Training with GPU

### ISSUE THREAD

**Issue by dev2y** [sovit-123/fasterrcnn-pytorch-training-pipeline#50]
What is your goto Hardware setup for training? 
Is it Windows desktop with NVidia GPU  or you usually run it on AWS/Azure?

**Comment by sovit-123** [comment]
@dev2y 
For most deep learning tasks, I use Ubuntu. I have a local RTX 3080 GPU which allows me to do some mid-high level experiments locally before any major push to projects.

**Comment by dev2y** [comment]
cool. thanks
