### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Noor-Kalibbala** [sovit-123/fasterrcnn-pytorch-training-pipeline#58]
Traceback (most recent call last):
  File "/home/noor/fasterrcnn-pytorch-training-pipeline/train.py", line 539, in <module>
    main(args)
  File "/home/noor/fasterrcnn-pytorch-training-pipeline/train.py", line 251, in main
    train_sampler = RandomSampler(train_dataset)
  File "/home/noor/anaconda3/envs/tf-gpu/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "

**Comment by sovit-123** [comment]
@Noor-Kalibbala 
It looks like the path to the data folders in the YAML file is wrong. Can you please check that again? They should be relative to the `fasterrcnn-pytorch-training-pipeline` directory, i.e., from where we execute the `train.py` file.

**Comment by Noor-Kalibbala** [comment]
@sovit-123 my configuration file is given below, 
```# Images and labels direcotry should be relative to train.py
TRAIN_DIR_IMAGES: '../data/Katunda_dataset/train'
TRAIN_DIR_LABELS: '../data/Katunda_dataset/train'
VALID_DIR_IMAGES: '../data/Katunda_dataset/valid'
VALID_DIR_LABELS: '../data/Katunda_dataset/valid'
TEST_DIR_IMAGES: '../data/Katunda_dataset/test'
TEST_DIR_LABELS: '../data/Katunda_dataset/test' 
# Class names.
CLASSES: ['Fruits brown spot',
'Fruits healthy',
'Fruits woodiness',
'Leaves brown spot',
'Leaves healthy',
'Leaves woodiness']
# Number of classes (object classes + 1 for background class in Faster RCNN).
NC: 6
# Whether to save the predictions of the validation set while training.
SAVE_VALID_PREDICTION_IMAGES: True
```

**Comment by Noor-Kalibbala** [comment]
@sovit-123 my configuration file is given below, 
```# Images and labels direcotry should be relative to train.py
TRAIN_DIR_IMAGES: '../data/Katunda_dataset/train'
TRAIN_DIR_LABELS: '../data/Katunda_dataset/train'
VALID_DIR_IMAGES: '../data/Katunda_dataset/valid'
VALID_DIR_LABELS: '../data/Katunda_dataset/valid'
TEST_DIR_IMAGES: '../data/Katunda_dataset/test'
TEST_DIR_LABELS: '../data/Katunda_dataset/test' 
# Class names.
CLASSES: ['Fruits brown spot',
'Fruits healthy',
'Fruits woodiness',
'Leaves brown spot',
'Leaves healthy',
'Leaves woodiness']
# Number of classes (object classes + 1 for background class in Faster RCNN).
NC: 6
# Whether to save the predictions of the validation set while training.
SAVE_VALID_PREDICTION_IMAGES: True
```

**Comment by Noor-Kalibbala** [comment]
can i use full paths instead

**Comment by Noor-Kalibbala** [comment]
I have solved it

**Comment by HAMZA12337** [comment]
how you solve it

**Comment by sovit-123** [comment]
Please check the image and label paths in the YAML file. Most probably, they do not point to the correct directory.

**Comment by HAMZA12337** [comment]
Please what is the format of annotations should be i get this results 

IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

My XML FORMAT

<annotation>
	<folder></folder>
	<filename>0_jpg.rf.952079b842be24cd0b6e52ab79585935.jpg</filename>
	<path>0_jpg.rf.952079b842be24cd0b6e52ab79585935.jpg</path>
	<source>
		<database>roboflow.ai</database>
	</source>
	<size>
		<width>416</width>
		<height>416</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>0</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<occluded>0</occluded>
		<bndbox>
			<xmin>249</xmin>
			<xmax>330</xmax>
			<ymin>252</ymin>
			<ymax>317</ymax>
		</bndbox>
	</object>
</annotation>

**Comment by sovit-123** [comment]
Take a look at this YAML file.
```
# Images and labels direcotry should be relative to train.py
TRAIN_DIR_IMAGES: '../input/Aquarium Combined.v2-raw-1024.voc/train'
TRAIN_DIR_LABELS: '../input/Aquarium Combined.v2-raw-1024.voc/train'
VALID_DIR_IMAGES: '../input/Aquarium Combined.v2-raw-1024.voc/valid'
VALID_DIR_LABELS: '../input/Aquarium Combined.v2-raw-1024.voc/valid'

# Class names.
CLASSES: [
    '__background__',
    'fish', 'jellyfish', 'penguin',
    'shark', 'puffin', 'stingray',
    'starfish'
]

# Number of classes (object classes + 1 for background class in Faster RCNN).
NC: 8

# Whether to save the predictions of the validation set while training.
SAVE_VALID_PREDICTION_IMAGES: True
```

Here `CLASSES` contain the class names that correspond to the `name` attribute in the XML file. In your XML file it is `0`, so your CLASSES should contain `[__background__, 0]`

**Comment by HAMZA12337** [comment]
thank you a lot

**Comment by sovit-123** [comment]
Welcome
