### ISSUE TITLE
How can I Implement SoftNMS 

### ISSUE THREAD

**Issue by Engineer-D** [sovit-123/fasterrcnn-pytorch-training-pipeline#78]
Please I want to be able to implement softNMS how can I go about it. Thanks

**Comment by sovit-123** [comment]
@Engineer-D 
This repository uses PyTorch Torchvision models where the NMS is already implemented in the model pipeline. Most probably you will need to edit the model code and then again load the trained weights properly to implement softNMS.

**Comment by Engineer-D** [comment]
Any hint on how I can I do that?

**Comment by Engineer-D** [comment]
will look into it

**Comment by Engineer-D** [comment]
If I find a solution will do well to let yall know
