### ISSUE TITLE
Negative Metric Report

### ISSUE THREAD

**Issue by aymuos15** [sovit-123/fasterrcnn-pytorch-training-pipeline#83]
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.019
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.018
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.026
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.057
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.058
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.057
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

What does negative mean in terms of Precision and Recall?

Sorry if this is already mentioned in the code.

**Comment by sovit-123** [comment]
This is happening because pycocotools does not find bounding boxes which are large in the dataset. For pycocotools large bunding boxes means at least 96x96 pixel boxes.

**Comment by aymuos15** [comment]
So essentially then, the model is working. Just that the bounding box sizes are small so that metric is not going to show anything?

Am I right in saying this?

**Comment by sovit-123** [comment]
@aymuos15 
Yes, if a dataset does not contain a specific bounding box shape, pycocotools will report -1 for that size.

**Comment by aymuos15** [comment]
Thanks a lot!
