### ISSUE TITLE
Supported image formats. 

### ISSUE THREAD

**Issue by aymuos15** [sovit-123/fasterrcnn-pytorch-training-pipeline#85]
I am working on some personal data on a personal environment which are in the form of **.tif** and the code is not working.

Is there any constraint on the type of image file? Works only on the regular .jpg .jpeg and .png?

Because, keeping everything the same, it is working on the data you have on the original colab. As in, I downloaded the data locally and it is working.

**Edit:** I tried converting one of the images to .tif and it did not read alongside the other .jpg images. I believe this seems to be the problem. Is there any fix? I tried searching the codebase but could not find any specific place where the image types are defined.

**Edit2**: I found the places the image formats were mentioned and have made the changes. You can delete this issue if you wish or can close it as well.

**Comment by sovit-123** [comment]
Thanks. I will try to push an update to support `.tif` format as well. I am closing the issue for now.
