### ISSUE TITLE
Training on a custom dataset - qt.qpa.plugin: Could not load the Qt platform plugin "xcb" even though it was found.

### ISSUE THREAD

**Issue by utility-aagrawal** [sovit-123/fasterrcnn-pytorch-training-pipeline#87]
Hi,

I was able to set up and run the smoke detection experiment on my machine. It's an Ubuntu 20.04 virtual machine. Now when I try to train the model on a custom dataset, I am getting the following error - 

![image](https://github.com/sovit-123/fasterrcnn-pytorch-training-pipeline/assets/140737044/6c9bc168-97e1-4dcf-b4d2-05908f84a005)

Can you advise? I am using the same virtual environment that I ran the smoke experiment on. I just changed the dataset and class names in .yaml file. I would really appreciate your help with this! Thanks!

**Comment by sovit-123** [comment]
If this is a cloud env, then please do this:
`pip uninstall opencv-python`
`pip uninstall opencv-python-headless`
`pip install -U opencv-python-headless`

In case, you are facing on a system where a screen (monitor is connected): 
`pip uninstall opencv-python`
`pip uninstall opencv-python-headless`
`pip install -U opencv-python`

However, that error really depends on the system and sometimes we may need to uninstall all the pyqt related packages and install OpenCV again.

**Comment by sovit-123** [comment]
Yes, `--vis-transformed` expects a screen connected. Basically, that shows the transformed inputs before the training begins so that the user can go through a visual debug that all the transforms are correct.

If this solves the issue, please consider closing it.

Thanks.

**Comment by utility-aagrawal** [comment]
Thanks @sovit-123! Makes sense! I'll try it on a machine where a screen is also connected.

**Comment by utility-aagrawal** [comment]
Resolved.
