### ISSUE TITLE
Defining augmentations

### ISSUE THREAD

**Issue by aymuos15** [sovit-123/fasterrcnn-pytorch-training-pipeline#95]
`    parser.add_argument(
        '-uta', '--use-train-aug', 
        dest='use_train_aug', 
        action='store_true',
        help='whether to use train augmentation, blur, gray, \
              brightness contrast, color jitter, random gamma \
              all at once'
    )`

Sorry for the novice questions, but could you please give a bit more context as to how to call these?

Example: only blur.

train.py: error: unrecognized arguments: blur

**Comment by aymuos15** [comment]
Hey! I actually did not want all the augmentations, I want only the blur. Hence my question.

**Comment by sovit-123** [comment]
At the moment, the codebase does not support individual augmentations. Most probably, the best for you now can be to comment out the augmentations that you don't need in `transforms.py`.

**Comment by sovit-123** [comment]
By default, the aspect ratio resizing does not happen for this codebase. All the images are resized to square size. So, if you pass 640, images are resized to 640x640. If you pass 800, images are resized to 800x800.
I am still trying to optimize the codebase such that the models will perform better with aspect ratio resizing.

**Comment by aymuos15** [comment]
Is there any way to avoid the resize?

**Comment by sovit-123** [comment]
Do you not want any type of resizing, be it aspect ratio or square?

**Comment by aymuos15** [comment]
Yes, I want to send the image as is. With the original size. They are large images. Compute isnt an issue.

**Comment by sovit-123** [comment]
In that case you can comment out the resizing part in the `dataset.py` file. Although in this case, the model may perform worse as it has not been pretrained to handle such cases.

**Comment by aymuos15** [comment]
Oh right, that makes sense. Thanks for that. I don't have enough the data i am using for retraining.
