### ISSUE TITLE
Question: ResNet50 Backbone weights

### ISSUE THREAD

**Issue by aymuos15** [sovit-123/fasterrcnn-pytorch-training-pipeline#97]
Is there any way to change the weights of the backbone? Assume I have my own pre-trained resnet50 on some other dataset? How would I go about doing this?

To note, I have classification weights of a resnet50 model. So I want to change the weights of only the backbone, not the entire fasterrcnn model itself. 

So is the below change (in comments where i use): `model_backbone.load_state_dict(torch.load('binary_classification_resnet18.pth'), strict=False)` 
the right way of going about it?

Ex:

```
def create_model(num_classes, pretrained=True, coco_model=False):
    # Load the pretrained ResNet18 backbone.
    model_backbone = torchvision.models.resnet18(weights='DEFAULT')
    ## model_backbone.load_state_dict(torch.load('binary_classification_resnet18.pth'), strict=False)

    conv1 = model_backbone.conv1
    bn1 = model_backbone.bn1
    relu = model_backbone.relu
    max_pool = model_backbone.maxpool
    layer1 = model_backbone.layer1
    layer2 = model_backbone.layer2
    layer3 = model_backbone.layer3
    layer4 = model_backbone.layer4

    backbone = nn.Sequential(
        conv1, bn1, relu, max_pool, 
        layer1, layer2, layer3, layer4
    )

    # We need the output channels of the last convolutional layers from
    # the features for the Faster RCNN model.
    # It is 512 for ResNet18.
    backbone.out_channels = 512

    # Generate anchors using the RPN. Here, we are using 5x3 anchors.
    # Meaning, anchors with 5 different sizes and 3 different aspect 
    # ratios.
    anchor_generator = AnchorGenerator(
        sizes=((32, 64, 128, 256, 512),),
        aspect_ratios=((0.5, 1.0, 2.0),)
    )

    # Feature maps to perform RoI cropping.
    # If backbone returns a Tensor, `featmap_names` is expected to
    # be [0]. We can choose which feature maps to use.
    roi_pooler = torchvision.ops.MultiScaleRoIAlign(
        featmap_names=['0'],
        output_size=7,
        sampling_ratio=2
    )

    # Final Faster RCNN model.
    model = FasterRCNN(
        backbone=backbone,
        num_classes=num_classes,
        rpn_anchor_generator=anchor_generator,
        box_roi_pool=roi_pooler
    )
    return model

if __name__ == '__main__':
    from model_summary import summary
    model = create_model(num_classes=81, pretrained=True, coco_model=True)
```

**Comment by sovit-123** [comment]
You are on the right path. But before that, you will have to change the initialization of the model. The line before that loads the Torchvision ResNet18. It should load your ResNet18 model and then you can load the weights. Remember to remove the classification head and just load the feature layers.

**Comment by aymuos15** [comment]
I used the normal pretrained resnet-18 as well. From torchvision. That shouldn't make a difference, right? 

Also, arent you already removing the classifier here:

```
backbone = nn.Sequential(
        conv1, bn1, relu, max_pool, 
        layer1, layer2, layer3, layer4
    )

    backbone.out_channels = 512
```

**Comment by sovit-123** [comment]
Yes, I am removing it. But I was talking about your custom trained backbone.

**Comment by aymuos15** [comment]
Alright. So to sum it up:

if I call the above lines exactly as they are (using the torch.load), then the backbone should change to custom weights right?

Thanks once again!

**Comment by sovit-123** [comment]
Yes, just remember to change path your weights file.
