### ISSUE TITLE
Add VGG16

### ISSUE THREAD

**Issue by samahwaleed** [sovit-123/fasterrcnn-pytorch-training-pipeline#99]
Dear Sir,

could you please implement VGG16 as a backbone to Faster R-CNN? It will help me in my research work. 

Thank you

**Comment by sovit-123** [comment]
Sure, I will try to add that.

**Comment by sovit-123** [comment]
@samahwaleed 
I have added the Faster RCNN VGG16 model.

**Comment by samahwaleed** [comment]
Thank you so much

**Comment by sovit-123** [comment]
Please close the issue in case you feel that your requirement is satisfied.
